name: Hello, World!
on:
  push:
    # Specify branch name
    branches:
      - master
    tags:
      - "v*"

jobs:
  # Job ID
  build:
    # Job name
    name: Greetings
    # Virtual machine
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v2
      - run: npm run test
