name: Hello, World!
on:
  push:
    # Specify branch name
    branches:
      - master
    tags:
      - "v*"

jobs:
  # Job ID
  build:
    # Job name
    name: Greetings
    # Virtual machine
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
